// Code generated by protoc-gen-go.
// source: netdata.proto
// DO NOT EDIT!

/*
Package teleport is a generated protocol buffer package.

It is generated from these files:
	netdata.proto

It has these top-level messages:
	NetDataProto
*/
package teleport

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type NetDataProto struct {
	Body             []byte  `protobuf:"bytes,1,req" json:"Body,omitempty"`
	Operation        *string `protobuf:"bytes,2,req" json:"Operation,omitempty"`
	UID              *string `protobuf:"bytes,3,req" json:"UID,omitempty"`
	From             *string `protobuf:"bytes,4,req" json:"From,omitempty"`
	To               *string `protobuf:"bytes,5,req" json:"To,omitempty"`
	Status           *int64  `protobuf:"varint,6,req" json:"Status,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NetDataProto) Reset()         { *m = NetDataProto{} }
func (m *NetDataProto) String() string { return proto.CompactTextString(m) }
func (*NetDataProto) ProtoMessage()    {}

func (m *NetDataProto) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *NetDataProto) GetOperation() string {
	if m != nil && m.Operation != nil {
		return *m.Operation
	}
	return ""
}

func (m *NetDataProto) GetUID() string {
	if m != nil && m.UID != nil {
		return *m.UID
	}
	return ""
}

func (m *NetDataProto) GetFrom() string {
	if m != nil && m.From != nil {
		return *m.From
	}
	return ""
}

func (m *NetDataProto) GetTo() string {
	if m != nil && m.To != nil {
		return *m.To
	}
	return ""
}

func (m *NetDataProto) GetStatus() int64 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}
